"""posts is a stub domain (content ships in Phase 8) but the router is real — slugged like
projects, so the document id should be the payload's slug, not an autogenerated one."""

from __future__ import annotations

from unittest.mock import patch

from fastapi.testclient import TestClient
from google.cloud.firestore_v1 import Client

from shared.api import make_app
from shared.crud import ContentService
from src.posts.repository import PostRepository
from src.posts.routes import get_posts_service
from src.posts.routes import router as posts_router

ADMIN = {"uid": "admin-1", "email": "admin@example.com", "admin": True}


def test_post_id_is_its_slug(db: Client, clean_collection: str) -> None:
    class ScratchRepo(PostRepository):
        collection = clean_collection

    app = make_app(posts_router, "test")
    app.dependency_overrides[get_posts_service] = lambda: ContentService(ScratchRepo(db))
    client = TestClient(app)

    with patch("shared.core.security.auth.verify_id_token", return_value=ADMIN):
        response = client.post(
            "/",
            json={"slug": "hello-world", "title": "Hello, World", "visibility": "draft"},
            headers={"Authorization": "Bearer x"},
        )
    assert response.status_code == 201
    assert response.json()["id"] == "hello-world"
